apiVersion: v1
kind: Template
labels:
  application: oshinko-python-spark
metadata:
  annotations:
    description: Create a buildconfig and imagestream using s2i and python spark src files in git.
    openshift.io/display-name: Apache Spark Python
  name: oshinko-python-spark-build
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    dockerImageRepository: ${APP_NAME}
    tags:
    - name: latest
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APP_NAME}:latest
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URI}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: radanalytics-pyspark:stable
      type: Source
      triggers: {}
parameters:
- description: 'Name for bc/is'
  name: APP_NAME
  required: true
- description: 'git url'
  name: GIT_URI
  required: true
- description: 'git branch/tag/commit'
  name: GIT_REF
  required: true
  value: master
- description: 'context-dir, name of py-file.'
  name: CONTEXT_DIR
