kind: Template
apiVersion: v1
template: data-loader
metadata:
  name: data-loader
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: ${JOB_NAME}
  spec:
    schedule: "*/2 * * * *"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              parent: cron-job-${JOB_NAME}
          spec:
            containers:
            - image: ${IMAGE}
              name: ${JOB_NAME}
              env:
              - name: AZ_TENANT_ID
                value: ${AZ_TENANT_ID}
              - name: AZ_CLIENT_ID
                value: ${AZ_CLIENT_ID}
              - name: AZ_CLIENT_SECRET
                value: ${AZ_CLIENT_SECRET}
              - name: AZ_STORE_NAME
                value: ${AZ_STORE_NAME}
            restartPolicy: Never
parameters:
- name: JOB_NAME
  required: true
- name: IMAGE
  required: true
- name: AZ_TENANT_ID
  required: false 
- name: AZ_CLIENT_ID
  required: false
- name: AZ_CLIENT_SECRET
  required: false
- name: AZ_STORE_NAME
  required: false
